name: Update docker tag to latest

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 */2 * *"

jobs:
  update_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Find latest tag & Update Dockerfile
        run: |
          LATEST_TAG=$(curl -s 'https://hub.docker.com/v2/repositories/library/ubuntu/tags' -H 'Content-Type: application/json' | jq -r '.results[]| .name' | grep jammy |head -n 1)
          echo "Latest tag: $LATEST_TAG"
          if [[ "$LATEST_TAG" != "$(cat docker/create-custom-user-ubuntu | grep 'FROM ubuntu:' | awk -F ':' '{print $2}')" ]]; then
            sed -i "s/FROM ubuntu:.*/FROM ubuntu:$LATEST_TAG/" docker/create-custom-user-ubuntu
          fi
      - name: Commit and push changes
        if: ${{ steps.update_image.outputs.modified == 'true' }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Update Ubuntu Jammy image"
          git push
